ALTER TABLE users ADD COLUMN IF NOT EXISTS bio text NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS location text NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS company text NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS website text NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS github text NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_revision integer NOT NULL DEFAULT 1;
